# Generated by Django 2.0.3 on 2018-05-25 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import project.analyzer.helper_functions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Text', 'Text'), ('Batch', 'Batch ')], max_length=40, verbose_name='type')),
                ('title', models.CharField(max_length=40, verbose_name='title')),
                ('created', models.DateField(auto_now_add=True, verbose_name='created')),
                ('author', models.TextField(blank=True, null=True, verbose_name='author')),
                ('total_word_count', models.IntegerField(blank=True, null=True, verbose_name='total_word_count')),
                ('dale_chall_score', models.CharField(blank=True, max_length=5, null=True, verbose_name='readability_batch')),
                ('unique_words', models.IntegerField(blank=True, null=True, verbose_name='unique_words_batch')),
                ('word_frequency', models.CharField(blank=True, max_length=6, null=True, verbose_name='word_frequency_batch')),
                ('word_unique_word_ratio', models.TextField(blank=True, null=True, verbose_name='word_unique_word_ratio')),
            ],
            options={
                'verbose_name': 'Analysis History',
                'verbose_name_plural': 'Analysis Histories',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='name')),
                ('created', models.DateField(auto_now_add=True, verbose_name='created')),
                ('date_modified', models.DateField(null=True, verbose_name='date_modified')),
                ('author', models.TextField(blank=True, null=True, verbose_name='author')),
                ('word_count', models.IntegerField(blank=True, null=True, verbose_name='word_count')),
                ('unique_words', models.IntegerField(blank=True, null=True, verbose_name='unique_words')),
                ('dale_chall', models.CharField(blank=True, max_length=5, null=True, verbose_name='dale-chall')),
                ('word_unique_word_ratio', models.TextField(blank=True, null=True, verbose_name='word_unique_word_ratio')),
            ],
            options={
                'verbose_name': 'Batch',
                'verbose_name_plural': 'Batches',
            },
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='title')),
                ('created', models.DateField(auto_now_add=True, null=True, verbose_name='created')),
                ('date_modified', models.DateField(blank=True, null=True, verbose_name='date_modified')),
                ('content', models.TextField(verbose_name='content')),
                ('author', models.TextField(blank=True, null=True, verbose_name='author')),
                ('word_count', models.IntegerField(blank=True, null=True, verbose_name='word_count')),
                ('unique_words', models.IntegerField(blank=True, null=True, verbose_name='unique_words')),
                ('dale_chall', models.CharField(blank=True, max_length=6, null=True, verbose_name='dale-chall')),
                ('word_unique_word_ratio', models.TextField(blank=True, null=True, verbose_name='word_unique_word_ratio')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40, verbose_name='first_name')),
                ('last_name', models.CharField(max_length=40, verbose_name='last_name')),
                ('email', models.CharField(max_length=100, verbose_name='email')),
                ('registration_code', models.CharField(blank=True, default=project.analyzer.helper_functions.code_generator, max_length=15, unique=True, verbose_name='registration_code')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='../profile_pictures/', verbose_name='profile_picture')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'UserProfile',
                'verbose_name_plural': 'UserProfiles',
            },
        ),
        migrations.AddField(
            model_name='batch',
            name='text_files',
            field=models.ManyToManyField(to='analyzer.Text', verbose_name='different_text_files'),
        ),
        migrations.AddField(
            model_name='batch',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='analysishistory',
            name='text_files',
            field=models.ManyToManyField(blank=True, related_name='histories', to='analyzer.Text', verbose_name='text'),
        ),
        migrations.AddField(
            model_name='analysishistory',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterUniqueTogether(
            name='text',
            unique_together={('author', 'title')},
        ),
    ]
